"""time

Revision ID: 05a22b023c20
Revises: 3495ed8fa576
Create Date: 2023-12-28 11:12:34.782274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a22b023c20'
down_revision = '3495ed8fa576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
