"""added date and blog_id columns

Revision ID: 6033470ec1ce
Revises: 3b41e9ca5f72
Create Date: 2023-12-27 14:56:57.606242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6033470ec1ce'
down_revision = '3b41e9ca5f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_bookings')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('blog_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('blog_id')
        batch_op.drop_column('date')

    op.create_table('_alembic_tmp_bookings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('from_address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('to_address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('persons_to_carry', sa.INTEGER(), nullable=False),
    sa.Column('luggage_to_carry', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('additional_text', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_bookings_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
